from django.test import TestCase
from models import Campus, Building, Classroom

CAMPUSES = {'SGW':'Sir George Williams Campus','LOY':'Loyola Campus'}

class CampusTest(TestCase):
	def setUp(self):
		for code, name in CAMPUSES:
			campuses.append(Campus.objects.create(code=code,name=name))
		SGW = Campus.objects.get(code='SGW')
		LOY = Campus.objects.get(code='LOY')
		H = SGW.buildings.create(code='H',name="Hall Building",notes="Across de Maisonneuve from LB.")
		H633 = H.classrooms.create(number="633",notes="Impossibly hidden on the NW corner. NTBCW H-633-1.")
		H407 = H.classrooms.create(number=407)

	def test_creation(self):
		"""
		Verifies the autogenerated objects.
		"""
		n = len( CAMPUSES.keys() )
		self.failUnlessEqual(Campus.objects.count(), n)
		SGW = Campus.objects.get(code_iequals='sgW')
		LOY = Campus.objects.get(code_iequals='Loy')
		self.failUnlessEqual(SGW.buildings.count(), 1)
		self.failUnlessEqual(LOY.buildings.count(), 0)
		H = Building.objects.get(code='H')
		self.failUnlessEqual(H.classrooms.count(), 2)

		self.failUnlessEqual(H in SGW.buildings.all(), True)

